//! # Task run time statistics
//!
//! Task run time is measured with a free-running 32-bit counter. Uptime comes from
//! `embassy-time` instead, because the core clock and with it the DWT cycle counter
//! stop while the executor sleeps.
//!
//! This library builds on the `trace` feature of `embassy-executor`. It tracks the cycle counts
//! for following components:
//!
//!  - Tasks
//!  - Executors, both interrupts and thread mode.
//!  - Interrupts
//!
//!  However, you need to instrument interrupt handlers which are not used to run interrupt
//!  executor yourself using the [interrupt_scope] function.
//!
//! ## Usage
//!
//! The `trace` and `metadata-name` features of `embassy-executor` are enabled by this crate.
//!
//! 1. Call [`init`] before the first measurement.
//! 2. Name each task before spawning it. Unnamed tasks are shown by their address.
//! 3. Measure interrupt handlers with [`interrupt_scope`], see below.
//! 4. Read the statistics, see below.
//!
//! ```ignore
//! let core = cortex_m::Peripherals::take().unwrap();
//! trace::init(core.DCB, core.DWT, core_clock_hz);
//!
//! let token = my_task().unwrap();
//! token.metadata().set_name("my_task");
//! spawner.spawn(token);
//! ```
//!
//! ## Reading the statistics
//!
//! [`print_stats`] prints a table with one row per task and interrupt and a summary.
//! [`print_stats_defmt`] prints the same content without alignment, but needs about 3 KB less
//! flash because it does not use `core::fmt`. The summary rows add up to the uptime:
//!
//! ```text
//! Task                Time [us]       %      Polls
//! ------------------------------------------------
//! main                      812    0.01          2
//! busy_worker           1530000   30.59        469
//! short_lived             15625    0.31          5 (ended)
//!
//! Interrupt           Time [us]       %      Calls
//! ------------------------------------------------
//! uart5_dummy             78125    1.56       1000
//!
//! Summary             Time [us]       %
//! ------------------------------------------------
//! tasks                 1797641   35.95
//! interrupts              78125    1.56
//! executor                 9870    0.19
//! idle + other          3114487   62.28
//! ------------------------------------------------
//! uptime                5000123
//! ```
//!
//! For custom processing, [`snapshot`] returns a copy of all counters. The critical section only
//! covers the copy, so processing it does not add to the interrupt latency.
//!
//! ```ignore
//! if let Some(stats) = trace::snapshot() {
//!     for (id, task) in &stats.tasks {
//!         let us = stats.ticks_to_us(task.ticks);
//!     }
//!     let idle_us = stats.idle_and_other_us();
//! }
//! ```
//!
//! ## Measuring interrupts
//!
//! Create the scope first thing in the handler. It measures until it is dropped:
//!
//! ```ignore
//! #[interrupt]
//! fn UART5() {
//!     let _scope = trace::interrupt_scope("UART5");
//!     // handler code
//! }
//! ```
//!
//! Handlers generated by `bind_interrupts!` of the HAL can not be instrumented. Write the handler
//! and the `Binding` implementation yourself instead, and forward to the HAL handler:
//!
//! ```ignore
//! use embassy_stm32::interrupt::typelevel::{Binding, Handler};
//!
//! #[derive(Copy, Clone)]
//! struct Irqs;
//!
//! // SAFETY: The handler below forwards the interrupt to the HAL handler.
//! unsafe impl Binding<interrupt::typelevel::USART3, usart::BufferedInterruptHandler<peripherals::USART3>> for Irqs {}
//!
//! #[interrupt]
//! fn USART3() {
//!     let _scope = trace::interrupt_scope("usart3");
//!     unsafe {
//!         <usart::BufferedInterruptHandler<peripherals::USART3> as Handler<interrupt::typelevel::USART3>>::on_interrupt();
//!     }
//! }
//! ```
//!
//! Interrupt handlers which run an interrupt executor should not be scoped. The executor hooks
//! already measure them.
//!
//! ## Limits
//!
//! - [`MAX_TASKS`], [`MAX_IRQS`] and [`MAX_NESTING`] size the static storage. Overflows are
//!   reported by [`print_stats`] and in the [`Snapshot`].
//! - Time of interrupt handlers without a scope is added to the context they preempted, or to
//!   [`Snapshot::idle_and_other_us`] if no context was active.
//! - A single task poll must not take longer than one counter wrap, about 67 s at 64 MHz.
//! - Single core Cortex-M only. Every hook takes a critical section.

use core::cell::RefCell;
use core::fmt::Write as _;
use core::marker::PhantomData;
use core::sync::atomic::{AtomicU32, Ordering};

use cortex_m::peripheral::{DCB, DWT, SCB};
use critical_section::Mutex;
use embassy_executor::ExecutorId;
use embassy_executor::raw::TaskRef;
use embassy_executor::raw::trace::Trace;
use embassy_time::Instant;
use heapless::index_map::FnvIndexMap;

/// Must be a power of two and at least the number of task slots in the program.
const MAX_TASKS: usize = 16;
/// Must be a power of two and at least the number of measured interrupts.
const MAX_IRQS: usize = 16;

/// Depth of the [`State::active_contexts`] stack.
///
/// An interrupt executor can preempt a lower priority executor or the thread executor while it
/// polls a task. Each executor which is active at the same time pushes itself and the task it
/// polls. Each measured interrupt handler pushes itself. So this must be at least twice the
/// number of executor priority levels plus the number of measured interrupt priority levels.
const MAX_NESTING: usize = 8;

/// Frequency of [`counter`], set by [`init`]. Zero means [`init`] was not called yet.
static COUNTER_HZ: AtomicU32 = AtomicU32::new(0);

/// Global because the trace hooks are free functions without any `self` argument.
///
/// The hooks are called from interrupt executors and interrupt handlers as well, so all
/// accesses happen inside a critical section.
static STATE: Mutex<RefCell<State>> = Mutex::new(RefCell::new(State::new()));

/// Enables the DWT cycle counter used for the measurements.
///
/// Tasks polled before this call are not measured.
pub fn init(mut dcb: DCB, mut dwt: DWT, core_clock_hz: u32) {
    dcb.enable_trace();
    // The Cortex-M7 DWT is software locked after reset.
    DWT::unlock();
    dwt.enable_cycle_counter();
    COUNTER_HZ.store(core_clock_hz, Ordering::Relaxed);
}

/// Single point to replace for cores without a DWT cycle counter, for example with a
/// free-running hardware timer. It must be 32 bits wide and must not wrap twice during a
/// single task poll.
fn counter() -> u32 {
    DWT::cycle_count()
}

/// Run time statistics of one task.
#[derive(Debug, Clone, Copy, Default)]
pub struct TaskStats {
    /// Set through the task metadata.
    pub name: Option<&'static str>,
    /// Counter ticks spent polling the task.
    pub ticks: u64,
    pub polls: u64,
    /// The entry is reset once the task ID is used again.
    pub ended: bool,
}

/// Run time statistics of one interrupt measured with [`interrupt_scope`].
#[derive(Debug, Clone, Copy, Default)]
pub struct IrqStats {
    pub name: Option<&'static str>,
    /// Counter ticks spent in the handler.
    pub ticks: u64,
    pub calls: u64,
}

#[derive(Clone, Copy)]
enum Context {
    Executor,
    Task(usize),
    /// Active exception number.
    Interrupt(usize),
}

/// State structure which is available globally through the [STATE] static.
///
/// This structure uses a bounded hash map for task and interrupt request statistics and a stack
/// structure for accounting tick/cycle increments. Embassy tasks are usually static and the number
/// of tasks is bounded in those systems, so this was considered sufficient for task tracing.
struct State {
    //// Task statistics hash map.
    tasks: FnvIndexMap<usize, TaskStats, MAX_TASKS>,
    /// Hardware interrupts statistics hash map.
    irqs: FnvIndexMap<usize, IrqStats, MAX_IRQS>,
    /// Contexts which were entered and not left yet. They can be nested because interrupt
    /// executors and measured interrupt handlers preempt other contexts.
    ///
    /// On every push and pop, the ticks since the previous push or pop are added to the top entry.
    /// The entries below only receive ticks again once they are on top.
    active_contexts: heapless::Vec<Context, MAX_NESTING>,
    last_count: u32,
    executor_ticks: u64,
    /// Ticks of ended tasks whose entries were reset or evicted. Kept so that this time does not
    /// end up in [`Snapshot::idle_and_other_us`].
    ended_task_ticks: u64,
    /// Contexts which did not fit into [`State::active_contexts`]. Their time is added to the
    /// innermost context which fit.
    untracked_nesting: u32,
    /// Stays set once [`State::untracked_nesting`] was used, for the warning in [`print_stats`].
    max_nesting_exceeded: bool,
    /// Tasks which did not fit into the map and are not measured.
    untracked_tasks: u32,
    /// Interrupts which did not fit into the map and are not measured.
    untracked_irqs: u32,
}

impl State {
    const fn new() -> Self {
        Self {
            tasks: FnvIndexMap::new(),
            irqs: FnvIndexMap::new(),
            active_contexts: heapless::Vec::new(),
            last_count: 0,
            executor_ticks: 0,
            ended_task_ticks: 0,
            untracked_nesting: 0,
            max_nesting_exceeded: false,
            untracked_tasks: 0,
            untracked_irqs: 0,
        }
    }

    // This helper method is called on every task [Self::enter] and [Self::leave] method call.
    fn add_elapsed_to_active(&mut self) {
        let now = counter();
        let elapsed = u64::from(now.wrapping_sub(self.last_count));
        self.last_count = now;
        match self.active_contexts.last() {
            Some(Context::Executor) => self.executor_ticks += elapsed,
            Some(Context::Task(id)) => {
                if let Some(task) = self.tasks.get_mut(id) {
                    task.ticks += elapsed;
                }
            }
            Some(Context::Interrupt(id)) => {
                if let Some(irq) = self.irqs.get_mut(id) {
                    irq.ticks += elapsed;
                }
            }
            None => (),
        }
    }

    fn enter(&mut self, context: Context) {
        self.add_elapsed_to_active();
        if self.untracked_nesting > 0 || self.active_contexts.push(context).is_err() {
            self.untracked_nesting += 1;
            self.max_nesting_exceeded = true;
        }
    }

    fn leave(&mut self) {
        self.add_elapsed_to_active();
        if self.untracked_nesting > 0 {
            self.untracked_nesting -= 1;
        } else {
            self.active_contexts.pop();
        }
    }

    fn enter_interrupt(&mut self, vector: usize, name: &'static str) {
        if !self.irqs.contains_key(&vector)
            && self.irqs.insert(vector, IrqStats::default()).is_err()
        {
            self.untracked_irqs = self.untracked_irqs.saturating_add(1);
        }
        if let Some(stats) = self.irqs.get_mut(&vector) {
            stats.name = Some(name);
            stats.calls += 1;
        }
        // Pushed even if untracked, so the time is not added to the preempted context.
        self.enter(Context::Interrupt(vector));
    }

    /// Returns the entry for a task which is about to be named or spawned.
    ///
    /// An ended entry belongs to a previous task, because IDs can be reused after a task
    /// ended. It is reset, including the name. If the map is full, an ended entry of another
    /// task is evicted. Returns `None` if there is none.
    fn get_or_insert_task(&mut self, id: usize) -> Option<&mut TaskStats> {
        if !self.tasks.contains_key(&id) {
            if self.tasks.len() == MAX_TASKS {
                let ended_id = self
                    .tasks
                    .iter()
                    .find(|(_, stats)| stats.ended)
                    .map(|(id, _)| *id);
                if let Some(ended_id) = ended_id {
                    if let Some(evicted) = self.tasks.remove(&ended_id) {
                        self.ended_task_ticks += evicted.ticks;
                    }
                } else {
                    self.untracked_tasks = self.untracked_tasks.saturating_add(1);
                    return None;
                }
            }
            // Can not fail, there is space now.
            let _ = self.tasks.insert(id, TaskStats::default());
        }
        let stats = self.tasks.get_mut(&id)?;
        if stats.ended {
            self.ended_task_ticks += stats.ticks;
            *stats = TaskStats::default();
        }
        Some(stats)
    }
}

fn with_state(f: impl FnOnce(&mut State)) {
    critical_section::with(|cs| f(&mut STATE.borrow_ref_mut(cs)));
}

struct Tracer;

impl Trace for Tracer {
    // Pushes the executor to the context stack.
    fn poll_start(_executor: ExecutorId) {
        with_state(|s| s.enter(Context::Executor));
    }

    // Add the task to the hash map.
    //
    // This might also evict a previously ended task if the map is full otherwise.
    fn task_new(_executor: ExecutorId, task: TaskRef) {
        with_state(|s| {
            let previous_run_ticks = s.get_or_insert_task(task.id().get()).map(|stats| {
                let ticks = stats.ticks;
                *stats = TaskStats {
                    name: stats.name,
                    ..Default::default()
                };
                ticks
            });
            if let Some(ticks) = previous_run_ticks {
                s.ended_task_ticks += ticks;
            }
        });
    }

    fn task_end(_executor: ExecutorId, task: TaskRef) {
        // Called before `task_exec_end` of the same poll, so the entry must stay.
        with_state(|s| {
            if let Some(stats) = s.tasks.get_mut(&task.id().get()) {
                stats.ended = true;
            }
        });
    }

    // Increments poll count and pushes a task to the context stack.
    fn task_exec_begin(_executor: ExecutorId, task: TaskRef) {
        let id = task.id().get();
        with_state(|s| {
            if let Some(stats) = s.tasks.get_mut(&id) {
                stats.polls += 1;
            }
            s.enter(Context::Task(id));
        });
    }

    // Pops the task from the context stack.
    fn task_exec_end(_executor: ExecutorId, _task: TaskRef) {
        with_state(State::leave);
    }

    // This is empty because we only care about polling having completed ([task_exec_end]) or
    // the task having ended ([task_end]).
    fn task_ready_begin(_executor: ExecutorId, _task: TaskRef) {}

    /// Pop the executor from the context stack.
    fn executor_idle(_executor: ExecutorId) {
        with_state(State::leave);
    }

    // Not needed. Idle time is part of the uptime minus all measured ticks.
    fn idle() {}

    fn task_name_set(task: TaskRef, name: &'static str) {
        with_state(|s| {
            if let Some(stats) = s.get_or_insert_task(task.id().get()) {
                stats.name = Some(name.trim_end_matches('\0'));
            }
        });
    }

    fn task_priority_set(_task: TaskRef, _priority: u8) {}

    fn task_deadline_set(_task: TaskRef, _deadline: u64) {}
}

embassy_executor::trace_impl!(Tracer);

/// Measures the current interrupt handler until the returned guard is dropped.
///
/// Create it first thing in the handler. The interrupt is identified by the active exception
/// number, `name` only labels its row in [`print_stats`]. Outside of an exception handler this
/// does nothing.
///
/// You do not need to use it in the handler of an interrupt executor. The executor and its tasks
/// are already measured by the executor hooks, so the interrupt would only get the few ticks
/// outside of the executor poll. It is harmless though, nothing is counted twice.
pub fn interrupt_scope(name: &'static str) -> InterruptScope {
    // SAFETY: Reading ICSR has no side effects. VECTACTIVE is read directly because
    // `SCB::vect_active` truncates it to 8 bits.
    let vector = (unsafe { (*SCB::PTR).icsr.read() } & 0x1ff) as usize;
    let entered = vector != 0;
    if entered {
        with_state(|s| s.enter_interrupt(vector, name));
    }
    InterruptScope {
        entered,
        _not_send: PhantomData,
    }
}

/// Leaves the interrupt context on drop, see [`interrupt_scope`].
///
/// It must be dropped in the handler which created it, otherwise the context stack gets out of
/// balance. It is not `Send` for that reason. Leaking it with `mem::forget` has the same effect.
#[must_use = "the interrupt is only measured until the guard is dropped"]
pub struct InterruptScope {
    entered: bool,
    _not_send: PhantomData<*const ()>,
}

impl Drop for InterruptScope {
    fn drop(&mut self) {
        if self.entered {
            with_state(State::leave);
        }
    }
}

/// Copy of all statistics at one point in time, see [`snapshot`].
#[derive(Debug, Clone)]
pub struct Snapshot {
    /// Keyed by task ID.
    pub tasks: FnvIndexMap<usize, TaskStats, MAX_TASKS>,
    /// Keyed by exception number.
    pub irqs: FnvIndexMap<usize, IrqStats, MAX_IRQS>,
    /// Counter ticks spent in executors outside of task polls.
    pub executor_ticks: u64,
    /// Counter ticks of ended tasks which are no longer in [`Snapshot::tasks`].
    pub ended_task_ticks: u64,
    pub uptime_us: u64,
    /// Frequency of all tick values.
    pub counter_hz: u32,
    /// Tasks which did not fit into [`Snapshot::tasks`] and were not measured.
    pub untracked_tasks: u32,
    /// Interrupt calls which did not fit into [`Snapshot::irqs`] and were not measured.
    pub untracked_irqs: u32,
    /// Some run times were added to the wrong context, see [`MAX_NESTING`].
    pub max_nesting_exceeded: bool,
}

impl Snapshot {
    pub fn ticks_to_us(&self, ticks: u64) -> u64 {
        let hz = u64::from(self.counter_hz);
        // Split so that the multiplication can not overflow, even for long uptimes.
        ticks / hz * 1_000_000 + ticks % hz * 1_000_000 / hz
    }

    /// Includes [`Snapshot::ended_task_ticks`].
    pub fn tasks_us(&self) -> u64 {
        let ticks: u64 = self.tasks.values().map(|stats| stats.ticks).sum();
        self.ticks_to_us(ticks + self.ended_task_ticks)
    }

    pub fn irqs_us(&self) -> u64 {
        self.ticks_to_us(self.irqs.values().map(|stats| stats.ticks).sum())
    }

    pub fn executor_us(&self) -> u64 {
        self.ticks_to_us(self.executor_ticks)
    }

    /// Everything which was not measured. Mostly sleep time, but also interrupt handlers without
    /// [`interrupt_scope`] which ran while no context was active, for example the time driver,
    /// and the startup time before [`init`].
    pub fn idle_and_other_us(&self) -> u64 {
        self.uptime_us
            .saturating_sub(self.tasks_us() + self.irqs_us() + self.executor_us())
    }
}

/// Returns a copy of all statistics, or `None` if [`init`] was not called.
///
/// Only the copy happens inside the critical section, so the interrupt latency does not depend
/// on what the caller does with it.
pub fn snapshot() -> Option<Snapshot> {
    let counter_hz = COUNTER_HZ.load(Ordering::Relaxed);
    if counter_hz == 0 {
        return None;
    }
    let snapshot = critical_section::with(|cs| {
        let s = STATE.borrow_ref(cs);
        Snapshot {
            tasks: s.tasks.clone(),
            irqs: s.irqs.clone(),
            executor_ticks: s.executor_ticks,
            ended_task_ticks: s.ended_task_ticks,
            uptime_us: Instant::now().as_micros(),
            counter_hz,
            untracked_tasks: s.untracked_tasks,
            untracked_irqs: s.untracked_irqs,
            max_nesting_exceeded: s.max_nesting_exceeded,
        }
    });
    Some(snapshot)
}

/// Prints [`snapshot`] as a table.
pub fn print_stats() {
    let Some(snapshot) = snapshot() else {
        defmt::warn!("trace: init was not called");
        return;
    };
    let uptime_us = snapshot.uptime_us;

    print_header("Task", "Polls");
    for (id, stats) in &snapshot.tasks {
        let us = snapshot.ticks_to_us(stats.ticks);
        let mut name = heapless::String::<16>::new();
        match stats.name {
            Some(n) => write!(name, "{:.16}", n).unwrap_or(()),
            None => write!(name, "{:#x}", id).unwrap_or(()),
        }
        print_row(format_args!(
            "{:<16} {:>12} {:>7} {:>10}{}",
            name,
            us,
            Percent::new(us, uptime_us),
            stats.polls,
            if stats.ended { " (ended)" } else { "" },
        ));
    }
    if !snapshot.irqs.is_empty() {
        defmt::println!("");
        print_header("Interrupt", "Calls");
    }
    for (vector, stats) in &snapshot.irqs {
        let us = snapshot.ticks_to_us(stats.ticks);
        let mut name = heapless::String::<16>::new();
        match stats.name {
            Some(n) => write!(name, "{:.16}", n).unwrap_or(()),
            None => write!(name, "vector {}", vector).unwrap_or(()),
        }
        print_row(format_args!(
            "{:<16} {:>12} {:>7} {:>10}",
            name,
            us,
            Percent::new(us, uptime_us),
            stats.calls,
        ));
    }
    defmt::println!("");
    print_header("Summary", "");
    for (name, us) in [
        ("tasks", snapshot.tasks_us()),
        ("interrupts", snapshot.irqs_us()),
        ("executor", snapshot.executor_us()),
        ("idle + other", snapshot.idle_and_other_us()),
    ] {
        print_row(format_args!(
            "{:<16} {:>12} {:>7}",
            name,
            us,
            Percent::new(us, uptime_us)
        ));
    }
    defmt::println!("{=str}", SEPARATOR);
    print_row(format_args!("{:<16} {:>12}", "uptime", uptime_us));
    print_warnings(&snapshot);
}

/// Prints the same content as [`print_stats`] with defmt formatting only.
///
/// The rows are not aligned. In exchange the `core::fmt` machinery is not linked in, as long as
/// [`print_stats`] is not used either.
pub fn print_stats_defmt() {
    let Some(snapshot) = snapshot() else {
        defmt::warn!("trace: init was not called");
        return;
    };
    let uptime_us = snapshot.uptime_us;

    for (id, stats) in &snapshot.tasks {
        let us = snapshot.ticks_to_us(stats.ticks);
        let ended = if stats.ended { " (ended)" } else { "" };
        match stats.name {
            Some(name) => defmt::println!(
                "task {=str}: {=u64} us, {}, {=u64} polls{=str}",
                name,
                us,
                Percent::new(us, uptime_us),
                stats.polls,
                ended
            ),
            None => defmt::println!(
                "task {=usize:#x}: {=u64} us, {}, {=u64} polls{=str}",
                id,
                us,
                Percent::new(us, uptime_us),
                stats.polls,
                ended
            ),
        }
    }
    for stats in snapshot.irqs.values() {
        let us = snapshot.ticks_to_us(stats.ticks);
        defmt::println!(
            "interrupt {=str}: {=u64} us, {}, {=u64} calls",
            stats.name.unwrap_or("?"),
            us,
            Percent::new(us, uptime_us),
            stats.calls
        );
    }
    for (name, us) in [
        ("tasks", snapshot.tasks_us()),
        ("interrupts", snapshot.irqs_us()),
        ("executor", snapshot.executor_us()),
        ("idle + other", snapshot.idle_and_other_us()),
    ] {
        defmt::println!("{=str}: {=u64} us, {}", name, us, Percent::new(us, uptime_us));
    }
    defmt::println!("uptime: {=u64} us", uptime_us);
    print_warnings(&snapshot);
}

fn print_warnings(snapshot: &Snapshot) {
    if snapshot.untracked_tasks > 0 {
        defmt::warn!(
            "{} tasks did not fit, increase MAX_TASKS",
            snapshot.untracked_tasks
        );
    }
    if snapshot.untracked_irqs > 0 {
        defmt::warn!(
            "{} interrupt calls did not fit, increase MAX_IRQS",
            snapshot.untracked_irqs
        );
    }
    if snapshot.max_nesting_exceeded {
        defmt::warn!("nesting exceeded MAX_NESTING, run times were added to the wrong context");
    }
}

/// Spans a full table row.
const SEPARATOR: &str = "------------------------------------------------";

fn print_header(name: &str, count: &str) {
    print_row(format_args!(
        "{:<16} {:>12} {:>7} {:>10}",
        name, "Time [us]", "%", count
    ));
    defmt::println!("{=str}", SEPARATOR);
}

/// defmt has no padding or alignment, so the rows are formatted with `core::fmt`.
fn print_row(args: core::fmt::Arguments) {
    let mut row = heapless::String::<80>::new();
    // A row which does not fit is printed truncated.
    let _ = row.write_fmt(args);
    defmt::println!("{=str}", row);
}

/// Percentage with two decimal places.
struct Percent(u64);

impl Percent {
    fn new(part: u64, total: u64) -> Self {
        Self(part * 10_000 / total.max(1))
    }
}

impl defmt::Format for Percent {
    fn format(&self, f: defmt::Formatter) {
        let fraction = self.0 % 100;
        defmt::write!(f, "{=u64}.{=u64}{=u64} %", self.0 / 100, fraction / 10, fraction % 10);
    }
}

impl core::fmt::Display for Percent {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        let mut s = heapless::String::<12>::new();
        write!(s, "{}.{:02}", self.0 / 100, self.0 % 100)?;
        f.pad(&s)
    }
}
